### ISSUE TITLE
Block and unblock clients

### ISSUE THREAD

**Issue by tiransa** [KoenZomers/UniFiApi#1]
is that unifi api sufficient  only for read data? i need to block and unblock clients by API

**Comment by KoenZomers** [comment]
In its current state it's read only. It is fairly simple to extend the code with update functionality though. Is this something you can do yourself or do you need a sample?

**Comment by tiransa** [comment]
yes i need sample

**Comment by KoenZomers** [comment]
@tiransa, not sure if you still need it as it has been a while since you asked for this. I finally found some time to create a sample on blocking and unblocking clients. I've added this functionality including a unit test that show how to use it end to end to version 1.0.1.0 which I've just published.
